steps:
  - name: gcr.io/cloud-builders/docker
    args: ['build',
    '--build-arg', 'BUILD_ENV=prod',
    '-t', 'gcr.io/$PROJECT_ID/zg-analytics-engine-python:$TAG_NAME', '.']

  - name: gcr.io/cloud-builders/kubectl
    args: ['apply', '-f', 'ci/stable/deployment.yaml']
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=asia-southeast1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=sl-cluster'

  - name: gcr.io/cloud-builders/kubectl
    args:
      ['set', 'image', 'deployment/zg-analytics-engine-python-deployment', 'zg-analytics-engine-python=gcr.io/$PROJECT_ID/zg-analytics-engine-python:$TAG_NAME']
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=asia-southeast1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=sl-cluster'

images: ['gcr.io/$PROJECT_ID/zg-analytics-engine-python:$TAG_NAME']
