apiVersion: apps/v1
kind: Deployment
metadata:
  name: zg-analytics-engine-python-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zg-analytics-engine-python
  template:
    metadata:
      labels:
        app: zg-analytics-engine-python
    spec:
      containers:
        - name: zg-analytics-engine-python
          image: gcr.io/smart-living-173506/zg-analytics-engine-python:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: zg-analytics-engine-python
  labels:
    app: zg-analytics-engine-python
spec:
  selector:
    app: zg-analytics-engine-python
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
  type: NodePort
